[RFR] fix/upgrade dependencies
KnpLabs/knp-react-app pull request #10
Opened 2019-01-04 16:47 UTC by jaljo

Upgraded dependencies of the project to the latest version.

2019-01-04 17:12 UTC, Djeg requested changes

2019-01-04 17:12 UTC, Djeg commented on README.md
> +$ cp .env.dist .env
Je suis pas super d'accord avec ce `.dist`. React de base ne versionne pas les `.env.*.local`, ce sont eux qui devrait override le `.env`. Le `.env` devrait être fournie par défaut pour toute application. Le truc qui est cool avec cette technique c'est que lors de l'installation pas besoin de ce `cp` :), ça marche "out of the box"

2019-01-04 17:13 UTC, NicolasNSSM commented
T'as fait ça avec npm-check-updates ?

2019-01-07 08:28 UTC, jaljo commented
Nan j'avais peur que ca pète tout du coup j'ai créé un nouveau projet avec les dépendances a jour et j'ai juste modifié le package.json du projet knp react app.

2019-01-07 08:32 UTC, Djeg approved these changes

2019-01-07 08:36 UTC, merged